import os
from semantic_router import Route, RouteLayer
from semantic_router.encoders import CohereEncoder
from dotenv import find_dotenv, load_dotenv


load_dotenv(find_dotenv())

def setup_routes():
   
    COHERE_API_KEY = os.getenv("COHERE_API_KEY")
    # print(f"COHERE_API_KEY: {COHERE_API_KEY}")

    # Initialize the CohereEncoder
    encoder = CohereEncoder()

    # Define routes 
    application_route = Route(
        name="APPLICATION_ROUTE",
        utterances=[
            "How do I apply for scholarship",
            "I need scholarship. What do I do",
            "Scholarship application process",
            "I want to apply for Scholarship application ",
            "I want to apply for Scholarship",
            "How can I apply for the scholarship?",
            "How can I apply for a scholarship?", 
"What is the scholarship application process?",
"What are the steps involved in applying for a scholarship?",
"How do I go about applying for scholarships?",
"I need a scholarship. What do I do?",
"I need financial assistance for education. How can I apply for scholarships?",
"What are the immediate steps I can take to apply for a scholarship?",
"Could you please explain the scholarship application procedure?",
"What are the formal requirements for applying for a scholarship?",
"I am interested in applying for scholarships. What is the first step?",
"How are scholarships applied for?",
"By what process can scholarships be obtained?",
"May I inquire about the scholarship application process?",
"Could you please provide me with information on how to apply for scholarships?",
"How can I determine if I am eligible for any scholarships?",
"What are the eligibility criteria for applying for scholarships?",
"Where can I find information on available scholarships?",
"How do I locate scholarships that I may be eligible for?", 
            "Can you guide me through the application process for a scholarship?", 
            "What steps are needed to apply for scholarships?", 
            "How do I start a scholarship application?", 
            "What is the procedure for applying for a scholarship?", 
            "What’s the process for submitting a scholarship application?", 
            "Where can I find instructions to apply for scholarships?", 
            "How do I begin the scholarship application process?", 
            "What are the requirements for applying for a scholarship?", 
            "What do I need to do to apply for a scholarship?", 
            "How do I initiate the process for scholarship application?", 
            "Can you explain how to apply for scholarships?", 
            "What’s the process for getting a scholarship?", 
            "How do I go about applying for scholarships?", 
            "What’s the correct way to apply for scholarships?", 
            "Where can I find information on scholarship applications?", 
            "What’s the best way to apply for scholarships?", 
            "How should I proceed to apply for a scholarship?", 
            "How do I make a scholarship application?", 
            "Can you help me apply for scholarships?", 
            "What’s the first step in a scholarship application?", 
            "Can I get guidance on how to apply for scholarships?", 
            "What should I do to submit a scholarship application?", 
            "Can you walk me through the steps to apply for scholarships?", 
            "How do I complete the scholarship application process?", 
            "How can I register for a scholarship application?", 
            "How does the scholarship application process work?", 
            "Can I apply for scholarships online?", 
            "What’s involved in applying for a scholarship?", 
            "Where do I submit my scholarship application?", 
            "How long does it take to apply for scholarships?", 
            "What platform is used to apply for scholarships?", 
            "Do I need to submit any forms to apply for a scholarship?", 
            "Is there an online portal for scholarship applications?", 
            "What’s the eligibility to apply for scholarships?", 
            "Are there specific dates for applying for scholarships?", 
            "Can you provide a link to the scholarship application form?", 
            "What are the deadlines for applying for scholarships?", 
            "How do I confirm my scholarship application was received?", 
            "Is there an application fee for scholarships?", 
            "Where can I find updates on my scholarship application process?", 
            "Can you help me fill out my scholarship application form?", 
            "Are there templates for scholarship applications?", 
            "What should I avoid while applying for scholarships?", 
            "Can I apply for multiple scholarships at once?", 
            "Do I need a recommendation letter to apply for scholarships?", 
            "What documents do I need to apply for scholarships?", 
            "Where can I track my scholarship application progress?", 
            "How do I resubmit my scholarship application if needed?",
            "Is the application process online or offline?", "Where can I find the application form?", "Are there specific courses or programs this scholarship supports?", "What happens if I miss the deadline?", "Are there any specific guidelines for filling out the application form?", "Do I need a referral or recommendation to apply?", "Are there any entrance exams required for the application?", "Is work experience necessary for eligibility?", "Are there any region-specific restrictions for applying?", "How will I be informed about the final decision?", "Okay, how do I apply for the scholarship?", "Hey, what’s the process to apply for scholarships?", "Can you tell me how to start the scholarship application?", "What are the steps for applying for a scholarship?", "Can you guide me through the application process?", "Where can I get the scholarship application form?", "How do I fill out the application?", "Is there an online form for scholarships?", "Do I need to pay anything to apply for the scholarship?", "Is there a deadline for scholarship applications?", "How do I know if I’m eligible to apply?", "Where exactly do I apply for scholarships?", "Can I apply for more than one scholarship?", "What’s the process for applying for financial aid?", "Can someone assist me with my application?", "How do I get started on my scholarship application?", "Is there a specific website for applications?", "Do I have to register before I apply?", "Can I apply offline for scholarships?", "Can I save my application and finish it later?", "Who should I contact if I need help with my application?", "How do I submit the application once it’s done?", "Is there a guide for filling out applications?", "What’s the first thing I need to do to apply?", "How long does it take to finish the process?", "Where can I get information on scholarships?", "How many scholarships am I allowed to apply for?", "Can international students also apply?", "Got any tips for applying for scholarships?", "Is the application process the same for all scholarships?", "Do I need an account for the application?", "Is there an application fee I need to pay?", "How do I find out if I’m allowed to apply?", "Are there any special instructions I should follow?", "How do I apply for government scholarships?", "Can I submit an incomplete application?", "What if I miss the deadline?", "Do I need to reapply every year?", "Can I reapply if I was rejected before?", "Can I apply for the scholarship before admission?", "How do I apply for a renewal of my scholarship?", "Is there a portal specifically for applying?", "Where can I find detailed guidelines for applications?", "Are group applications allowed?", "Can I track the progress of my application?", "Can I use the same application for different scholarships?", "How soon should I start the application?", "Are applications accepted throughout the year?", "Do I need a reference to apply?", "How do I apply for merit-based scholarships?", "Can I apply for a need-based scholarship?", "What’s the easiest way to apply?", "Is the process different for postgraduate scholarships?", "How do I confirm that my application was submitted?", 
            "What should I include in my application?", 
            "Can I get a paper form to apply?",
            "How can I apply for the scholarship?", 
            "Okay, How can I apply for the scholarship?", 
            "What’s the process to apply for the scholarship?", 
            "Okay, What’s the process to apply for the scholarship?", 
            "How do I start the scholarship application?", 
            "Okay, How do I start the scholarship application?", 
            "What are the steps to apply for a scholarship?", 
            "Okay, What are the steps to apply for a scholarship?", 
            "Can you guide me on the scholarship application?", 
            "Okay, Can you guide me on the scholarship application?", 
            "Where can I find the scholarship application form?", 
            "Okay, Where can I find the scholarship application form?", 
            "How do I fill out the scholarship application?", 
            "Okay, How do I fill out the scholarship application?", 
            "Is there an online form to apply for scholarships?", 
            "Okay, Is there an online form to apply for scholarships?", 
            "Do I need to pay to apply for the scholarship?", 
            "Okay, Do I need to pay to apply for the scholarship?", 
            "Is there a deadline to apply for the scholarship?", 
            "Okay, Is there a deadline to apply for the scholarship?", 
            "How do I know if I’m eligible to apply?", 
            "Okay, How do I know if I’m eligible to apply?", 
            "Where do I go to apply for a scholarship?", 
            "Okay, Where do I go to apply for a scholarship?", 
            "Can I apply for multiple scholarships?", 
            "Okay, Can I apply for multiple scholarships?", 
            "What’s the procedure to apply for financial aid?", 
            "Okay, What’s the procedure to apply for financial aid?", 
            "Can someone help me with the application process?", 
            "Okay, Can someone help me with the application process?", 
            "How can I get started with my scholarship application?", 
            "Okay, How can I get started with my scholarship application?", 
            "Is there a website for scholarship applications?", 
            "Okay, Is there a website for scholarship applications?", 
            "Do I need to register to apply for the scholarship?", 
            "Okay, Do I need to register to apply for the scholarship?", 
            "Can I apply for a scholarship offline?", 
            "Okay, Can I apply for a scholarship offline?", 
            "Can I save my application and complete it later?", 
            "Okay, Can I save my application and complete it later?", 
            "Who can I contact for help with my application?", 
            "Okay, Who can I contact for help with my application?", 
            "How do I submit the scholarship application?", 
            "Okay, How do I submit the scholarship application?", 
            "Is there a guide for applying for scholarships?", 
            "Okay, Is there a guide for applying for scholarships?", 
            "What’s the first step in applying for a scholarship?", 
            "Okay, What’s the first step in applying for a scholarship?", 
            "How long does the application process take?", 
            "Okay, How long does the application process take?", 
            "Where do I find information about scholarship applications?", 
            "Okay, Where do I find information about scholarship applications?",     
            "How many scholarships can I apply for?", 
            "Okay, How many scholarships can I apply for?", 
            "Can international students apply for the scholarship?", 
            "Okay, Can international students apply for the scholarship?", 
            "Are there any tips for applying for scholarships?", 
            "Okay, Are there any tips for applying for scholarships?", 
            "Is the application process different for different scholarships?", 
            "Okay, Is the application process different for different scholarships?",  
            "Do I need an account to apply for scholarships?", 
            "Okay, Do I need an account to apply for scholarships?", 
            "Is there an application fee?", 
            "Okay, Is there an application fee?", 
            "How do I find out if I can apply?", 
            "Okay, How do I find out if I can apply?", 
            "Are there any special instructions for application?", 
            "Okay, Are there any special instructions for application?", 
            "How do I apply for a government scholarship?", 
            "Okay, How do I apply for a government scholarship?", 
            "Can I apply for a scholarship with incomplete details?", 
            "Okay, Can I apply for a scholarship with incomplete details?", 
            "What happens if I miss the application deadline?", 
            "Okay, What happens if I miss the application deadline?", 
            "Do I need to apply every year?", 
            "Okay, Do I need to apply every year?", 
            "Can I reapply for a scholarship?", 
            "Okay, Can I reapply for a scholarship?", 
            "Can I apply for a scholarship before admission?", 
            "Okay, Can I apply for a scholarship before admission?", 
            "How do I apply for renewal of the scholarship?", 
            "Okay, How do I apply for renewal of the scholarship?", 
            "Is there a specific portal for scholarship applications?", 
            "Okay, Is there a specific portal for scholarship applications?", 
            "Where can I find the scholarship application guidelines?", 
            "Okay, Where can I find the scholarship application guidelines?", 
            "Are group applications allowed for scholarships?", 
            "Okay, Are group applications allowed for scholarships?", 
            "Can I track my scholarship application progress?", 
            "Okay, Can I track my scholarship application progress?", 
            "Can I use the same application for different scholarships?", 
            "Okay, Can I use the same application for different scholarships?", 
            "How soon should I apply for the scholarship?", 
            "Okay, How soon should I apply for the scholarship?", 
            "Are applications accepted year-round?", 
            "Okay, Are applications accepted year-round?", 
            "Do I need a reference to apply for a scholarship?", 
            "Okay, Do I need a reference to apply for a scholarship?", 
            "How do I apply for merit-based scholarships?", 
            "Okay, How do I apply for merit-based scholarships?", 
            "Can I apply for a need-based scholarship?", 
            "Okay, Can I apply for a need-based scholarship?", 
            "What’s the easiest way to apply for scholarships?", 
            "Okay, What’s the easiest way to apply for scholarships?", 
            "Is the application process different for postgraduate scholarships?", 
            "Okay, Is the application process different for postgraduate scholarships?", 
            "How do I confirm my scholarship application submission?", 
            "Okay, How do I confirm my scholarship application submission?", 
            "What should I include in my scholarship application?", 
            "Okay, What should I include in my scholarship application?", 
            "Are application forms available offline?", 
            "Okay, Are application forms available offline?",
            "How do I know if my application has been successfully submitted?"

        ],
        score_threshold=0.7
    )
    
    documents_route = Route(
        name="DOCUMENTS_ROUTE",
        utterances=[
            "What documents are required for applying for scholarship",
            "How do I submit documents for scholarship",
            "What documents are required to apply for scholarships?",
            "What documents are required for scholarship applications?",
"What documents do I need to submit for a scholarship?",
"What are the required documents for scholarship applications?",
"How do I submit the necessary documents for a scholarship?",
"What type of documents are typically required for scholarship applications?",
"Are there specific documents required for this particular scholarship?",
"What supporting documentation is needed for my scholarship application?",
"How do I submit the required documents for a scholarship?",
"Where should I submit the scholarship documents?",
"What is the process for submitting scholarship documents?",
"Can I submit documents electronically?",
"Could you please provide a list of required documents for scholarship applications?",
"What is the acceptable method for submitting scholarship documents?",
"How are scholarship documents submitted?",
"By what means can scholarship documents be submitted?",
"May I inquire about the required documents for scholarship applications?",
"Could you please inform me of the document submission process?", 
            "Can you provide a list of necessary documents for scholarships?", 
            "What paperwork is needed for scholarship applications?", 
            "What supporting documents do I need for scholarships?", 
            "Are there specific forms needed to apply for scholarships?", 
            "What are the document requirements for scholarships?", 
            "How do I know what documents to submit for scholarships?", 
            "Can I get a checklist of required scholarship documents?", 
            "What is the documentation process for scholarships?", 
            "Are transcripts required for scholarship applications?", 
            "Do I need to submit any ID for scholarship applications?", 
            "Are academic records necessary for scholarships?", 
            "How do I prepare my documents for scholarship applications?", 
            "Do I need a letter of recommendation for scholarships?",  
            "What financial documents are needed for scholarships?", 
            "Can I submit scanned copies of documents for scholarships?", 
            "What happens if I miss a required document for scholarships?", 
            "Where can I upload my scholarship documents?", 
            "Is there a template for scholarship documents?",  
            "Are digital documents accepted for scholarships?", 
            "What formats are allowed for scholarship documents?", 
            "What should I include in my scholarship application file?", 
            "How do I verify my scholarship documents are complete?", 
            "Do I need proof of citizenship for scholarships?", 
            "What’s the deadline for submitting scholarship documents?",  
            "Can I mail my scholarship documents physically?", 
            "Where can I get help preparing scholarship documents?", 
            "What’s the procedure to upload additional documents?", 
            "Do I need both hard and soft copies of documents?", 
            "Is an income certificate needed for scholarships?", 
            "What happens if I upload incorrect documents?", 
            "Can I preview my document submission for scholarships?", 
            "Are there size limits for scholarship document uploads?", 
            "Do I need an affidavit for scholarships?", 
            "What’s the process for resubmitting missing documents?", 
            "Do scholarships require scanned or photographed documents?",
            "Okay, What documents are needed for a scholarship application?", "Do I need to submit documents for a scholarship?", "Okay, Do I need to submit documents for a scholarship?", "How do I upload my documents for a scholarship?", "Okay, How do I upload my documents for a scholarship?", "What are the document requirements for scholarships?", "Okay, What are the document requirements for scholarships?", "Are certified copies required for scholarship applications?", "Okay, Are certified copies required for scholarship applications?", "Do I need a transcript to apply for a scholarship?", "Okay, Do I need a transcript to apply for a scholarship?", "Are bank statements required for scholarships?", "Okay, Are bank statements required for scholarships?", "Can I submit documents online?", "Okay, Can I submit documents online?", "Where do I upload my scholarship documents?", "Okay, Where do I upload my scholarship documents?", "Are ID proofs required for scholarships?", "Okay, Are ID proofs required for scholarships?", "Do I need a recommendation letter for scholarships?", "Okay, Do I need a recommendation letter for scholarships?", "What should I do if I don’t have all the required documents?", "Okay, What should I do if I don’t have all the required documents?", "Is a cover letter necessary for scholarships?", "Okay, Is a cover letter necessary for scholarships?", "Can I submit documents after applying?", "Okay, Can I submit documents after applying?", "Are there specific formats for scholarship documents?", "Okay, Are there specific formats for scholarship documents?", "Is an essay mandatory for scholarships?", "Okay, Is an essay mandatory for scholarships?", "What is the size limit for uploaded documents?", "Okay, What is the size limit for uploaded documents?", "Can I mail my scholarship documents?", "Okay, Can I mail my scholarship documents?", "Is a birth certificate required for scholarships?", "Okay, Is a birth certificate required for scholarships?", "Do I need to notarize my documents?", "Okay, Do I need to notarize my documents?", "Are scanned copies acceptable?", "Okay, Are scanned copies acceptable?", "Is proof of income required for scholarships?", "Okay, Is proof of income required for scholarships?", "How do I check if my documents were received?", "Okay, How do I check if my documents were received?", "Can I send additional documents after submission?", "Okay, Can I send additional documents after submission?", "What happens if my documents are incomplete?", "Okay, What happens if my documents are incomplete?", "Are photographs needed for the application?", "Okay, Are photographs needed for the application?", "Is a resume necessary for scholarships?", "Okay, Is a resume necessary for scholarships?", "Do I need a personal statement for scholarships?", "Okay, Do I need a personal statement for scholarships?", "Are application fees required with the documents?", "Okay, Are application fees required with the documents?", "Can I submit documents in another language?", "Okay, Can I submit documents in another language?", "Is a passport copy needed for scholarships?", "Okay, Is a passport copy needed for scholarships?", "Are test scores mandatory for scholarships?", "Okay, Are test scores mandatory for scholarships?", "Can I submit temporary documents?", "Okay, Can I submit temporary documents?", "Do I need academic certificates for scholarships?", "Okay, Do I need academic certificates for scholarships?", "How do I combine multiple documents for upload?", "Okay, How do I combine multiple documents for upload?", "Are handwritten documents accepted?", "Okay, Are handwritten documents accepted?", "Do I need a tax return statement for scholarships?", "Okay, Do I need a tax return statement for scholarships?", "Is proof of address required?", "Okay, Is proof of address required?", "Are affidavits necessary for scholarships?", "Okay, Are affidavits necessary for scholarships?", "What kind of supporting documents are needed?", "Okay, What kind of supporting documents are needed?", "Do I need a medical certificate for scholarships?", "Okay, Do I need a medical certificate for scholarships?", "How do I organize my scholarship documents?", "Okay, How do I organize my scholarship documents?", "Are there deadlines for submitting documents?", "Okay, Are there deadlines for submitting documents?", "Can I submit documents in person?", "Okay, Can I submit documents in person?", "Are hard copies required for scholarships?", "Okay, Are hard copies required for scholarships?", "Is there a checklist for scholarship documents?", "Okay, Is there a checklist for scholarship documents?", "Are duplicate documents allowed?", "Okay, Are duplicate documents allowed?", "Can I submit older versions of documents?", "Okay, Can I submit older versions of documents?", "Is an enrollment letter necessary for scholarships?", "Okay, Is an enrollment letter necessary for scholarships?", "Do I need parental consent for scholarships?", "Okay, Do I need parental consent for scholarships?", "Are scanned documents accepted for submission?", "Okay, Are scanned documents accepted for submission?", "How do I submit confidential documents?", "Okay, How do I submit confidential documents?", "Is an English translation needed for foreign documents?", "Okay, Is an English translation needed for foreign documents?", "Can I withdraw documents after submission?", "Okay, Can I withdraw documents after submission?", "Are work experience certificates required?", "Okay, Are work experience certificates required?", "How do I compress large document files?", "Okay, How do I compress large document files?", "Do I need multiple copies of documents?", "Okay, Do I need multiple copies of documents?", "Are original documents needed for verification?", "Okay, Are original documents needed for verification?", "What’s the process to submit missing documents?", 
            "Okay, What’s the process to submit missing documents?",
            "Do I need to submit original documents or photocopies?", "Is a passport-sized photograph required? If yes, what size?", "Do I need to provide proof of income?", "What are the specifications for uploading scanned documents?", "Is an ID proof necessary? If yes, which ones are accepted?", "Is there a specific format for the documents?", "Do I need to submit a birth certificate?", "Are bank account details required during application?", "Do I need to provide proof of residency?", "Are there any affidavits or declarations I need to submit?", "Is there a checklist of documents I can refer to before submission?", "Do documents need to be attested or notarized?", "Can I submit documents in my regional language?", "What should I do if I don’t have a required document?", "How do I ensure my documents are uploaded successfully?", "So, what documents do I need to apply for a scholarship?", "Do I have to submit any documents for scholarships?", "How do I upload my documents?", "What are the document requirements?", "Are certified copies needed for applications?", "Do I need my transcript to apply?", "Are bank statements part of the required documents?", "Can I submit my documents online?", "Where should I upload my documents?", "Do I need an ID proof for scholarships?", "Are recommendation letters required?", "What if I don’t have all the required documents?", "Is a cover letter necessary for scholarships?", "Can I submit my documents after the application?", "Is there a specific format for submitting documents?", "Do I need to write an essay for this?", "Is there a size limit for uploaded documents?", "Can I mail the documents instead of uploading them?", "Is a birth certificate necessary?", "Do I have to notarize my documents?", "Are scanned copies acceptable?", "Do I need proof of income?", "How do I know if my documents were received?", "Can I send more documents after submission?", "What happens if I submit incomplete documents?", "Are photos needed?", "Do I have to attach my resume?", "Is a personal statement required?", "Do I need to pay any application fees for submitting documents?", "Can I send documents in another language?", "Do I need a passport copy for this?", "Are test scores part of the document list?", "Can I submit temporary documents?", "Are academic certificates needed?", "How do I combine multiple documents for upload?", "Are handwritten documents acceptable?", "Do I need my tax return statement?", "Is proof of address required?", "Do I need an affidavit for this?", "What supporting documents should I include?", "Is a medical certificate necessary?", "How should I organize my documents?", "Is there a deadline for submitting documents?", "Can I submit them in person?", "Are hard copies required?", "Is there a checklist of required documents?", "Can I send duplicate copies?", "What if my documents are outdated?", "Do I need an enrollment letter?", "Is parental consent required?", "Are scanned documents okay?", "How do I submit confidential documents?", "Do I need an English translation for foreign documents?", "Can I withdraw my documents?", "Are work experience certificates required?", "How can I compress large files?", "Do I need multiple copies of my documents?", "Will I need to verify original documents?", "What’s the process to send in missing documents?", "What’s the importance of a 10th marksheet for the application?", "Do I really need to submit my 12th marksheet?", "Why is the entrance exam rank required for the scholarship?", "How do I get a family income certificate?", "What should I do if I’ve lost my 10th marksheet?", "Can I submit a provisional 12th marksheet instead?", "Is there a specific format for the family income certificate?", "Where do I upload my entrance exam rank details?", "Do I need to submit originals or photocopies of my marksheets?", "What happens if my family income certificate is outdated?", "Can I submit my entrance rank later if I don’t have it now?", "Do I need to notarize the 10th and 12th marksheets?", "Is a self-attested copy of the family income certificate enough?", "What should I do if my family income certificate is not ready?", "Can I submit alternative proof of income instead of a certificate?", "Is there a deadline to submit these documents?", "How do I check if my documents meet the requirements?", "What if the family income certificate is in a regional language?", "Do I need to attach all pages of the marksheets?", "How do I verify that my entrance rank submission is complete?", "Is a scanned copy of the documents acceptable?", "Will my application be rejected if any of these documents are missing?", "Do I need to combine all these documents into a single file?", "Can I submit my documents via email?", "What’s the best way to ensure my documents are submitted correctly?", "Are any additional documents required apart from these?", "Is there a size limit for uploading the scanned documents?", "What should I do if my marksheets have errors in the name?", "Is it mandatory to submit both 10th and 12th marksheets?", "Do I need a recent family income certificate or is an old one acceptable?", "How do I get my family income certificate verified?", "Can I use my rank card instead of an entrance rank certificate?", "Is it necessary to submit both rank and income proof?", "Do I need to include any attestation from my school?", "Can I submit my documents in person instead of online?", "What if my entrance rank is from a different year?", "Are scanned marksheets valid for submission?", "Will I be notified if my documents are incomplete?", "How do I know if my documents have been accepted?", "Is there a checklist to verify these documents?", "Are there any tips for scanning these documents effectively?", "What’s the most common mistake in submitting these documents?", "How do I name the files for submission?", "Can I submit multiple family income certificates if needed?", "Do I need to provide any affidavit with the documents?", "Is it okay to submit color or black-and-white scans?", "How recent should the family income certificate be?", "Are digital copies of the marksheets acceptable?", "Can I include additional achievements with my entrance rank?", "Do I need to compress the document files before submitting them?", "Is there any priority given to specific documents?", "Should I prepare a covering letter for these documents?", "Can I re-upload the documents if there’s an issue?", "How will I know if the family income certificate meets the criteria?", "Are there any special instructions for uploading these documents?", "What do I do if my 10th or 12th marksheet is not legible?", "Can I use a scanned PDF file instead of individual images?", "Should I submit my entrance rank with a signature from the exam authority?", 
            "How do I ensure my family income certificate is accepted without issues?",
            "What documents do I need to prepare for applying?", "Can you list the specific documents required for this process?", "Are there any forms I need to fill out along with the documents?", "Where can I find details about the required documents?", "How do I check if my documents are complete?", "What happens if I miss submitting a document?", "Do I need to upload the documents online or submit them physically?", "Is there a checklist for the required documents?", "Do I need to get my documents verified before submission?", "What’s the first document I should prepare for the application?", "Can I submit the documents after the application deadline?", "Are scanned copies of the documents acceptable?", "How recent should the documents be?", "Is there a specific format for the documents I submit?", "Do I need to combine all documents into a single file?", "Should I prepare any supporting documents in addition to the main ones?", "Can I get examples of correctly prepared documents?", "What if I don’t have all the documents right now?", "Are the documents the same for all applicants?", "Can someone else submit my documents on my behalf?", "How do I organize my documents for submission?", "What’s the best way to prepare my documents for upload?", "Are there any special tips for ensuring document approval?", "How do I name the files when uploading the documents?", "Can I submit additional documents to strengthen my application?", "What’s the most common mistake when submitting documents?", "Is there a sample family income certificate I can refer to?", "Are there specific size limits for document uploads?", "Can I use digital copies of my certificates?", "Should I include an introduction letter with my documents?", "Do I need to submit documents in a specific order?", "How do I verify that my documents meet the requirements?", "Are there any priority documents I should focus on?", "What’s the turnaround time for document verification?", "Do I need to provide transcripts along with marksheets?", "Are bilingual documents acceptable for submission?", "How do I ensure my documents don’t get rejected?", "What should I do if I don’t have the required entrance exam rank?", "Should the documents be self-attested?", "Can I include documents related to extracurricular achievements?", "Are photocopies of the documents sufficient?", "Where can I check the status of my submitted documents?", "How do I fix issues with rejected documents?", "What format should I use to upload the documents (PDF, JPG, etc.)?", "Do I need to submit any affidavits along with the documents?", "Is it mandatory to submit proof of identity?", "Can I submit documents in regional languages?", "Are notarized documents required for the application?", "Do I need an official stamp on any of the documents?", "Is there a tutorial for uploading documents?", "How do I handle technical issues during document submission?", "What’s the procedure for replacing incorrect documents?", "Do I need to submit hard copies of the documents as well?", "Are there any specific guidelines for submitting academic certificates?", "What proof of address is accepted for this process?", "How do I ensure my documents are legible after scanning?", "Is there an acknowledgment receipt for submitted documents?", 
            "What’s the deadline for submitting all required documents?"


        ],
        score_threshold=0.7
    )
    
    status_route = Route(
        name="STATUS_ROUTE",
        utterances=[
            "What is the status of my application",
            "Current status",
            "Application status",
            "Scholarship status",
            "What is the status of my application?",
"What is the current status of my application?",
"What is the application status?",
"What is the scholarship status?",
"Could you please provide me with an update on the status of my application?",
"I would like to inquire about the current status of my scholarship application.",
"What is the status of the application I submitted?",
"What is the current status of my application being reviewed?",
"May I inquire about the current status of my scholarship application?",
"Could you please let me know the status of my application?",
"Has my application been reviewed?",
"What’s the status of my scholarship application?", 
"How can I check the progress of my application?", 
"What is the update on my scholarship request?", 
"Can you tell me the current state of my application?", 
"Has my scholarship application been processed?", 
"Where is my scholarship application currently?", 
"What’s the latest update on my scholarship status?", 
"What’s the condition of my application right now?", 
"Can you provide the current status of my application?", 
"How do I verify the status of my application?", 
"Has my application been reviewed yet?", 
"What stage is my scholarship application in?", 
"Is my scholarship application still under review?", 
"Can you update me on my scholarship application progress?", 
"How do I track the status of my application?", 
"What’s the decision on my scholarship application?", 
"Has my scholarship application been approved yet?", 
"Can you confirm if my application was received?", 
"What does the portal say about my scholarship status?", 
"How long does it take to get a status update?", 
"Can I expect any news about my scholarship soon?", 
"Is there any pending action for my application?", 
"Has my application been forwarded to the committee?", 
"What’s the decision timeline for my scholarship application?", 
"Where can I see detailed updates about my application?", 
"What’s the final status of my scholarship request?", 
"Have there been any updates to my application?", 
"When will I receive the final verdict on my scholarship?", 
"Is my application currently active or closed?", 
"Are there any issues with my scholarship application?", 
"Has my scholarship been awarded yet?", 
"What’s holding up my scholarship approval?", 
"Can you escalate my application review?", 
"What’s the pending status for my scholarship?", 
"What happens next for my scholarship application?", 
"Can you give me a status breakdown for my application?", 
"How do I resolve delays in my scholarship review?", 
"What does the current update mean for my scholarship?", 
"Has my scholarship funding been approved?", 
"When can I expect the scholarship disbursement?", 
"Has my application been marked as complete?", 
"Is my scholarship award in progress?", 
"What happens after my scholarship is approved?",
"Okay, How can I check my application status?", "What’s the current status of my scholarship application?", "Okay, What’s the current status of my scholarship application?", "Is my scholarship application approved?", "Okay, Is my scholarship application approved?", "How do I know if my application is being processed?", "Okay, How do I know if my application is being processed?", "Can you provide an update on my application?", "Okay, Can you provide an update on my application?", "When will I hear back about my scholarship application?", "Okay, When will I hear back about my scholarship application?", "Is there a way to track my application?", "Okay, Is there a way to track my application?", "How long does it take to process the application?", "Okay, How long does it take to process the application?", "Has my scholarship been accepted?", "Okay, Has my scholarship been accepted?", "Can I check my status online?", "Okay, Can I check my status online?", "What’s the status of my financial aid application?", "Okay, What’s the status of my financial aid application?", "Have my documents been verified?", "Okay, Have my documents been verified?", "Is there a hotline for application status?", "Okay, Is there a hotline for application status?", "What does ‘under review’ mean for my application?", "Okay, What does ‘under review’ mean for my application?", "What’s the meaning of ‘pending’ in application status?", "Okay, What’s the meaning of ‘pending’ in application status?", "Will I get a notification when my application is approved?", "Okay, Will I get a notification when my application is approved?", "Can I check the status without my application ID?", "Okay, Can I check the status without my application ID?", "What’s the status of my renewal application?", "Okay, What’s the status of my renewal application?", "How do I find out why my application was rejected?", "Okay, How do I find out why my application was rejected?", "Has my scholarship payment been released?", "Okay, Has my scholarship payment been released?", "When will I get a decision on my application?", "Okay, When will I get a decision on my application?", "How can I follow up on my application?", "Okay, How can I follow up on my application?", "Can I check my application status offline?", "Okay, Can I check my application status offline?", "Is there a delay in processing applications?", "Okay, Is there a delay in processing applications?", "What are the reasons for application delays?", "Okay, What are the reasons for application delays?", "Can I see the history of my application status?", "Okay, Can I see the history of my application status?", "Will I be informed if my status changes?", "Okay, Will I be informed if my status changes?", "How do I get proof of my application approval?", "Okay, How do I get proof of my application approval?", "Is there a way to expede my application process?", "How often is the status updated online?", "Okay, How often is the status updated online?", "Is there a timeline for application approval?", "Okay, Is there a timeline for application approval?", "Can I call to know my application status?", "Okay, Can I call to know my application status?", "What does ‘processing’ mean in application status?", "How can I check if my scholarship was awarded?", "Okay, How can I check if my scholarship was awarded?", "Has my application been shortlisted?", "Okay, Has my application been shortlisted?", "How do I know if my application is complete?", "Okay, How do I know if my application is complete?", "Is there a confirmation for submitted applications?", "Okay, Is there a confirmation for submitted applications?", "Okay, What should I do if my application is stuck?", "How long will the status show as pending?", "Okay, How long will the status show as pending?", "Is my scholarship award letter ready?", "Okay, Is my scholarship award letter ready?", "Has my application moved to the next stage?", "Okay, Has my application moved to the next stage?", "Why is my application status on hold?", "Okay, Why is my application status on hold?", "Can I request an update on my application?", "Okay, Can I request an update on my application?", "Why hasn’t my application status changed?", "Okay, Why hasn’t my application status changed?", "What should I do if my status is incorrect?", "Okay, What should I do if my status is incorrect?", "Is my application under final review?", "Okay, Is my application under final review?", "When will I get a response to my application?", "Okay, When will I get a response to my application?", "Can I view the status history for my application?", "Okay, Can I view the status history for my application?", "Is there a confirmation message after approval?", "Okay, Is there a confirmation message after approval?", "What’s the next step after approval?", "Okay, What’s the next step after approval?", "How do I find out if my scholarship is disbursed?", 
"Okay, How do I find out if my scholarship is disbursed?",
"What happens if my application is rejected?", "Can I appeal or request reconsideration if my application is rejected?", "Is there a helpline number or email for status inquiries?", "Will I receive an acknowledgment after submitting my application?", "Is there a final status confirmation process?", "Can I make corrections if my status shows errors?", "How will I be informed if my scholarship is approved?", "How can I check my application status?", "What’s the current status of my scholarship application?", "Is my scholarship application approved?", "How do I know if my application is being processed?", "Can you provide an update on my application?", "When will I hear back about my scholarship application?", "Is there a way to track my application?", "How long does it take to process the application?", "Has my scholarship been accepted?", "Can I check my status online?", "What’s the status of my financial aid application?", "Have my documents been verified?", "How will I know if my application is rejected?", "Is there a hotline for application status?", "What does ‘under review’ mean for my application?", "Can I appeal a rejected application?", "Is there a portal to check my scholarship status?", "What’s the meaning of ‘pending’ in application status?", "How do I fix an issue with my application status?", "Will I get a notification when my application is approved?", "Can I check the status without my application ID?", "What’s the status of my renewal application?", "How do I find out why my application was rejected?", "Is my application eligible for re-evaluation?", "Has my scholarship payment been released?", "When will I get a decision on my application?", "How can I follow up on my application?", "Can I check my application status offline?", "Is there a delay in processing applications?", "What are the reasons for application delays?", "How do I resolve a pending application?", "Can I see the history of my application status?", "Will I be informed if my status changes?", "How do I get proof of my application approval?", "How often is the status updated online?", "Is there a timeline for application approval?", "Can I call to know my application status?", "What does ‘processing’ mean in application status?", "How can I check if my scholarship was awarded?", "Has my application been shortlisted?", "How do I know if my application is complete?", "Is there a confirmation for submitted applications?", "How can I fix errors in my application?", "What should I do if my application is stuck?", "How long will the status show as pending?", "Is my scholarship award letter ready?", "Has my application moved to the next stage?", "Why is my application status on hold?", "Can I request an update on my application?", "Why hasn’t my application status changed?", "What should I do if my status is incorrect?", "Is my application under final review?", "When will I get a response to my application?", "Can I view the status history for my application?", "Is there a confirmation message after approval?", "What’s the next step after approval?", 
"How do I find out if my scholarship is disbursed?",
"What does 'document verification in process' indicate?",
"What does document verification in process indicate?"
],
        score_threshold=0.7
    )
    
    other_relevant_route = Route(
        name="OTHER_RELEVANT",
        utterances=[
            "Any other application-related questions",
            "Can I edit my application",
            "Okay, can I edit my application",
            "Can I update my application",
            "Can I edit my application after submission?",
        ],
        score_threshold=0.7
    )
    
    # Add all routes to a list
    routes = [application_route, documents_route, status_route, other_relevant_route]
    
    # Set up RouteLayer with encoder
    rl = RouteLayer(encoder=encoder, routes=routes)
    return rl

# Setup routes at the global level
rl = setup_routes()

def handle_user_query(user_prompt):
    
    # Function to handle user queries and determine the route.

    route = rl(user_prompt)
    
    if route:
        return {
            'response': f"Handling query related to {route.name}.",
            'route_name': route.name,
            'status': 'SUCCESS'
        }
    else:
        return {
            'response': 'The question does not match our criteria. Please ask another question or contact support for more help.',
            'status': 'FAILED'
        }


if __name__ == "__main__":
    while(True):
        user_question = input("Enter your question: ")
        result = handle_user_query(user_question)
        print(result)
